# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Image generation tools for DevPulse agent."""

import time
import uuid
from google import genai
from google.genai import types
from google.cloud import storage
from google.adk.tools import ToolContext

BUCKET_NAME = "devpulse-assets-qwiklabs-gcp-01-d85174ee446b"


def generate_system_diagram(prompt: str, tool_context: ToolContext = None) -> str:
    """Generates an architecture diagram, system topology illustration, or technical infographic.

    Args:
        prompt: Detailed description of the system architecture, component topology, or IT status diagram to generate.
        tool_context: Context provided by the framework to store session artifacts.

    Returns:
        Public HTTPS URL of the generated diagram image.
    """
    try:
        client = genai.Client(location="global")
        response = client.models.generate_content(
            model="gemini-3.1-flash-lite-image",
            contents=prompt,
        )

        candidates = getattr(response, "candidates", [])
        if not candidates or not candidates[0].content or not candidates[0].content.parts:
            return "Error: No image content generated by model."

        first_part = candidates[0].content.parts[0]
        inline_data = getattr(first_part, "inline_data", None)
        if not inline_data or not inline_data.data:
            return "Error: Model response did not contain inline image bytes."

        img_bytes = inline_data.data
        mime_type = inline_data.mime_type or "image/png"
        ext = "png" if "png" in mime_type else "jpg"

        unique_id = uuid.uuid4().hex[:8]
        timestamp = int(time.time())
        filename = f"diagram_{timestamp}_{unique_id}.{ext}"

        # 1. Save artifact so it shows up in Playground's Artifacts panel (if tool_context provided)
        if tool_context is not None:
            part = types.Part.from_bytes(data=img_bytes, mime_type=mime_type)
            tool_context.save_artifact(filename=filename, artifact=part)

        # 2. Upload exact image bytes directly to Cloud Storage bucket (no local file)
        storage_client = storage.Client()
        bucket = storage_client.bucket(BUCKET_NAME)
        object_path = f"generated_diagrams/{filename}"
        blob = bucket.blob(object_path)
        blob.upload_from_string(img_bytes, content_type=mime_type)

        public_url = f"https://storage.googleapis.com/{BUCKET_NAME}/{object_path}"
        return f"Successfully generated diagram image.\nPublic URL: {public_url}"

    except Exception as e:
        return f"Image generation error: {str(e)}"
